apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitlab-runner
rules:
- apiGroups: [""]
#- apiGroups: ["", "extensions", "apps"]
#- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
