stages:
  - deploy

variables:
  # Don't use default since we need extra permissions for deployment
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner
  JUPYTERHUB_CHART_VERSION: v0.7-2560dad
  JUPYTERHUB_DEPLOYMENT_NAME: kubernetes-runner-helm-test
  JUPYTERHUB_NAMESPACE: gitlab

deploy_staging:
  stage: deploy
  image: manics/kube-helm:latest
  before_script:
    - kubectl config view
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm repo update
    - helm repo list
    - helm list
    - helm delete --purge $JUPYTERHUB_DEPLOYMENT_NAME || true
  script:
    - helm repo list
    - >
        helm install --namespace=$JUPYTERHUB_NAMESPACE
        jupyterhub/jupyterhub
        --version=$JUPYTERHUB_CHART_VERSION
        --name=$JUPYTERHUB_DEPLOYMENT_NAME
        -f jupyterhub-config.yaml
        --set proxy.secretToken "$SECRET_JUPYTERHUB_PROXY_TOKEN"
  environment:
    name: staging
    url: https://idr-testing.openmicroscopy.org
  only:
  - master
