stages:
  - deploy

variables:
  JUPYTERHUB_CHART_VERSION: jupyterhub-v0.7-2560dad
  JUPYTERHUB_DEPLOYMENT_NAME: kubernetes-runner-helm-test

deploy_staging:
  stage: deploy
  image: manics/kube-helm:latest
  before_script:
    - kubectl config view
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm repo update
    - helm list
    - helm delete --purge $JUPYTERHUB_DEPLOYMENT_NAME || true
  script:
    - >
        helm install jupyterhub/jupyterhub
        --version=$JUPYTERHUB_CHART_VERSION
        --name=$JUPYTERHUB_DEPLOYMENT_NAME
        -f jupyterhub-config.yaml
  environment:
    name: staging
    url: https://idr-testing.openmicroscopy.org
  only:
  - master
