stages:
  - deploy

variables:
  JUPYTERHUB_CHART_VERSION: jupyterhub-v0.7-2560dad

deploy_staging:
  stage: deploy
  image: manics/kube-helm:latest
  before_script:
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm repo update
    - helm list
  script:
    - >
        helm upgrade --install jupyterhub/jupyterhub
        --version=$JUPYTERHUB_CHART_VERSION
        --name=kubernetes-runner-helm-test
        -f jupyterhub-config.yaml
  environment:
    name: staging
    url: https://idr-testing.openmicroscopy.org
  only:
  - master
