# Common parameters for all stages
image: manics/kube-helm:helmfile

stages:
  # Staging is run automatically when master is updated
  # Deletes an existing deployment before installing
  - deploy_staging
  # Public (no login) production requires a manual trigger
  # Upgrades if already installed
  - deploy_production_public
  # VAE production requires a manual trigger
  # Upgrades if already installed
  - deploy_production_vae

variables:
  # Don't use default since we need extra permissions for deployment
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner

before_script:
  - helm list

# Deployment commands
script:
  - helmfile --hide-args --selector deployment=$DEPLOYMENT sync --args '--wait --timeout=1200'
  - sh gitlab-ci/test.sh
  # TODO: Check we can run singleuser servers

deploy_staging:
  stage: deploy_staging
  before_script:
    - helm list
    - helm delete --purge jupyterhub-staging || true
  environment:
    name: staging-staging
    url: https://idr-training.openmicroscopy.org/staging
  only:
  - master

deploy_production_public:
  stage: deploy_production
  environment:
    name: production-public
    url: https://idr-training.openmicroscopy.org/public
  only:
  - master
  when: manual

deploy_production_vae:
  stage: deploy_production
  environment:
    name: production-vae
    url: https://idr-training.openmicroscopy.org/vae
  only:
  - master
  when: manual
