######################################################################
# Common settings

image: manics/kube-helm:helmfile

stages:
  - deploy_staging
  - deploy_production

variables:
  # Don't use default since we need extra permissions for deployment
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner

before_script:
  - helm list


######################################################################
# Jobs

# Staging is run automatically when master is updated
# Deletes an existing deployment before installing
deploy_staging:
  stage: deploy_staging
  before_script:
    - helm list
    - helm delete --purge jupyterhub-staging || true
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: staging-staging
    url: https://idr-training.openmicroscopy.org/staging
  only:
  - master

# Public (no login) production requires a manual trigger
# Upgrades if already installed
deploy_production_public:
  stage: deploy_production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-public
    url: https://idr-training.openmicroscopy.org/public
  only:
  - master
  when: manual

# VAE production requires a manual trigger
# Upgrades if already installed
deploy_production_vae:
  stage: deploy_production
  script:
    - sh gitlab-ci/deploy.sh
    # TODO: Check we can run singleuser servers
  environment:
    name: production-vae
    url: https://idr-training.openmicroscopy.org/vae
  only:
  - master
  when: manual
