stages:
  - deploy

variables:
  # Don't use default since we need extra permissions for deployment
  KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: gitlab-runner
  JUPYTERHUB_CHART_VERSION: v0.7-2560dad
  JUPYTERHUB_DEPLOYMENT_NAME: kubernetes-runner-helm-test
  JUPYTERHUB_NAMESPACE: gitlab
  # Since we're running inside a Kubernetes pod we can use internal DNS
  JUPYTERHUB_STAGING_URL: http://proxy-public/gitlab-test

deploy_staging:
  stage: deploy
  image: manics/kube-helm:latest
  before_script:
    - kubectl config view
    - helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    - helm repo update
    - helm repo list
    - helm list
    - helm delete --purge $JUPYTERHUB_DEPLOYMENT_NAME || true
  script:
    - >
        helm install
        jupyterhub/jupyterhub
        --version=$JUPYTERHUB_CHART_VERSION
        --namespace=$JUPYTERHUB_NAMESPACE
        --name=$JUPYTERHUB_DEPLOYMENT_NAME
        -f jupyterhub-config.yaml
        --wait --timeout 1200
        --set proxy.secretToken=$SECRET_JUPYTERHUB_PROXY_TOKEN
    - i=0
    - until (curl --fail -L $JUPYTERHUB_STAGING_URL/hub/api || [[ $i -gt 60 ]]); do
        sleep 10;
        let i++;
        echo "Waited ${i}0 seconds";
      done
    - curl --fail -s $JUPYTERHUB_STAGING_URL/hub/api | grep version
    # TODO: Check we can run singleuser servers

  environment:
    name: staging
    url: https://idr-testing.openmicroscopy.org
  only:
  - master
