# Common configuration
RELEASE_COMMON: &RELEASE_COMMON
  chart: jupyterhub/jupyterhub
  version: v0.7-28aad23

repositories:
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

releases:

  - <<: *RELEASE_COMMON
    name: jupyterhub-staging
    namespace: jupyterhub-staging
    labels:
      deployment: staging
      application: staging
    values:
      - jupyterhub-config.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"

  - <<: *RELEASE_COMMON
    name: jupyterhub-public
    namespace: jupyterhub-public
    labels:
      deployment: production
      application: public
    values:
      - jupyterhub-config.yaml
      - jupyterhub-public.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"

  - <<: *RELEASE_COMMON
    name: jupyterhub-vae
    namespace: jupyterhub-vae
    labels:
      deployment: production
      application: vae
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"
      - name: auth.github.clientId
        value: "{{ env \"SECRET_GITHUB_CLIENTID\" }}"
      - name: auth.github.clientSecret
        value: "{{ env \"SECRET_GITHUB_CLIENTSECRET\" }}"

  - <<: *RELEASE_COMMON
    name: jupyterhub-vae-aai
    namespace: jupyterhub-vae-aai
    labels:
      deployment: production
      application: vae-aai
    values:
      - jupyterhub-config.yaml
      - jupyterhub-vae-aai.yaml
    set:
      - name: proxy.secretToken
        value: "{{ env \"SECRET_JUPYTERHUB_PROXY_TOKEN\" }}"
      - name: singleuser.extraEnv.IDR_PASSWORD
        value: "{{ env \"SECRET_IDR_PASSWORD\" }}"
      - name: hub.extraEnv.OAUTH_CLIENT_ID
        value: "{{ env \"SECRET_AAI_CLIENTID\" }}"
      - name: hub.extraEnv.OAUTH_CLIENT_SECRET
        value: "{{ env \"SECRET_AAI_CLIENTSECRET\" }}"

  - name: idr-analysis-website
    namespace: idr-analysis-website
    chart: ./charts/idr-analysis-website
    labels:
      deployment: production
      application: website
    set:
      - name: ingress.hosts.0
        value: idr-training.openmicroscopy.org
      - name: image.pullPolicy
        value: Always

  - name: prometheus
    namespace: monitoring
    chart: stable/prometheus
    version: 6.3.3
    labels:
      deployment: production
      application: monitoring
    values:
      - prometheus-public.yaml

  - name: prometheus-auth
    namespace: monitoring
    chart: ./charts/kubernetes-secret
    labels:
      deployment: production
      application: monitoring
    set:
      - name: data.auth
        # value: {{ env "SECRET_PROMETHEUS_AUTH_HTPASSWD" }}
        value: bW9uaXRvcmluZzokYXByMSRHeVBYcWo2ZSRncmdhV1IzYnRZMjlFcEdEM0xyNGkwCg==
    # To create this value:
    # htpasswd -bc auth monitoring monitoring
    # base64 auth

  - name: grafana
    namespace: monitoring
    chart: stable/grafana
    version: 1.3.0
    labels:
      deployment: production
      application: monitoring
    values:
      - grafana-public.yaml
    set:
      - name: env.GF_AUTH_GITHUB_CLIENT_ID
        value: "{{ env \"SECRET_GRAFANA_GITHUB_CLIENTID\" }}"
      - name: env.GF_AUTH_GITHUB_CLIENT_SECRET
        value: "{{ env \"SECRET_GRAFANA_GITHUB_SECRET\" }}"


    # kubectl get secret --namespace monitoring grafana -o jsonpath="{.data.admin-password}" | base64 -d ; echo


  # - name: monitoring-oauth2
  #   namespace: monitoring
  #   chart: ./charts/oauth2-proxy
  #   version: 0.1.0
  #   labels:
  #     deployment: production
  #     application: monitoring
  #   values:
  #     - oauth2-proxy.yaml
  #   set:
  #     - name: github.clientId
  #       value: "{{ env \"SECRET_MONITORING_GITHUB_CLIENTID\" }}"
  #     - name: github.clientSecret
  #       value: "{{ env \"SECRET_MONITORING_GITHUB_CLIENTSECRET\" }}"
