apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
#kind: ClusterRole
metadata:
  name: gitlab
rules:
- apiGroups: [""]
#- apiGroups: ["", "extensions", "apps"]
#- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
