apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
#kind: ClusterRoleBinding
metadata:
  name: gitlab-runner
  namespace: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  #kind: ClusterRole
  name: gitlab-runner
  #name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitlab-runner
  namespace: gitlab
