apiVersion: rbac.authorization.k8s.io/v1beta1
#kind: RoleBinding
kind: ClusterRoleBinding
metadata:
  name: gitlab
roleRef:
  apiGroup: rbac.authorization.k8s.io
  #ind: Role
  kind: ClusterRole
  #name: gitlab
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: gitlab
  namespace: gitlab
