# https://gitlab.com/charts/charts.gitlab.io/blob/master/charts/gitlab-runner/values.yaml
# helm upgrade --install --namespace gitlab gitlab-runner -f gitlab-runner/helm-config.yaml gitlab/gitlab-runner

gitlabUrl: https://gitlab.com/
runnerRegistrationToken: # Secret
rbac:
  create: true
  clusterWideAccess: true
